### ISSUE TITLE
Add report issue / feedback link in document

### ISSUE THREAD

**Issue by wenwei202** [leptonai/leptonai-sdk#55]
**Is your feature request related to a problem? Please describe.**
Yes. Encountered issues following QuickStart and want to submit feedback.

**Describe the solution you'd like**
An explicit url in the QuickStart document on where to submit issues instead of having an imperceptible Github icon at the far corner.

**Describe alternatives you've considered**
Guess and Google Lepton AI github

**Additional context**

**Comment by Yangqing** [comment]
Thanks for reporting - link in the doc added.
